powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/CreateDeviceRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/DeleteDeviceRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/SendPushMessageBatchRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/TestCampaignRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/UpdateDeviceStatusRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/CampaignResponse.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/DeleteCampaignResponse.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/CampaignController.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/DeviceController.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/PushSendingController.java
Modified names, formatted code, added documentation.
Also merged with remote repo.
=> Implemented client methods (Fix #16), other changes.

powerauth-push-server/src/main/java/io/getlime/push/controller/rest/CampaignController.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/DeviceController.java, powerauth-push-server/src/main/java/io/getlime/push/controller/web/WebAdminController.java, powerauth-push-server/src/main/java/io/getlime/push/repository/AppCredentialRepository.java, powerauth-push-server/src/main/java/io/getlime/push/repository/PushCampaignDeviceRepository.java, powerauth-push-server/src/main/java/io/getlime/push/repository/PushCampaignRepository.java, powerauth-push-server/src/main/java/io/getlime/push/repository/PushCampaignUserRepository.java, powerauth-push-server/src/main/java/io/getlime/push/repository/PushDeviceRepository.java, powerauth-push-server/src/main/java/io/getlime/push/repository/PushMessageRepository.java, powerauth-push-server/src/main/java/io/getlime/push/repository/converter/PushMessageStatusConverter.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/AppCredentialEntity.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushCampaignDeviceEntity.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushCampaignEntity.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushCampaignUserEntity.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushDeviceEntity.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushMessageEntity.java, powerauth-push-server/src/main/java/io/getlime/push/service/PushSenderService.java
Changed class names representing database entities to avoid possible conflicts.
=> Refactoring, changed class names.

powerauth-push-docs/sql/mysql/create_push_server_schema.sql, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/PushDeviceController.java, powerauth-push-server/src/main/java/io/getlime/push/repository/PushDeviceRepository.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/AppCredentialEntity.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushCampaignEntity.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushCampaignUserEntity.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushDeviceRegistrationEntity.java, powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushMessageEntity.java, powerauth-push-server/src/main/java/io/getlime/push/service/PushMessageSenderService.java, powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingCallback.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmClient.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/model/FcmSendRequest.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/model/FcmSendResponse.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/model/base/FcmResult.java
=> Fix #25, Implemented FCM server response handling, Fix #31 Set Nullabillities

powerauth-push-server/pom.xml
=> Update Pushy library

powerauth-push-server/src/main/java/io/getlime/push/configuration/PowerAuthWebServiceConfiguration.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/AdministrationController.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/PushDeviceController.java
Required changes related to SOAP versioning:
https://github.com/wultra/powerauth-server/issues/175
=> Fix #169: Crypto 3.0: Versioning of web service interfaces

powerauth-push-client/pom.xml, powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java, powerauth-push-server/src/main/java/io/getlime/push/configuration/BatchSendingConfiguration.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/PushCampaignController.java, powerauth-push-server/src/main/java/io/getlime/push/controller/web/WebAdminController.java, powerauth-push-server/src/main/java/io/getlime/push/errorhandling/DefaultExceptionHandler.java, powerauth-push-server/src/main/java/io/getlime/push/repository/serialization/JSONSerialization.java, powerauth-push-server/src/main/java/io/getlime/push/service/PushMessageSenderService.java, powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmClient.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmModelConverter.java
This pull requests improves error handling and logging:
- Fix #168: swallowed cause exception
- Logging switched to slf4j similarly as in other PowerAuth backends
=> Fix #168: swallowed cause exception

docs/Push-Server-API.md, powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/GetApplicationDetailRequest.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/AdministrationController.java
This pull request contains multiple fixes of administration API:
- Fix #205: Document new admin API endpoints
- Update HTTP methods (do not always use POST like in PA server)
- Fix JSON serialization issue for includeIos and includeAndroid methods
=> Fix #205: Document new admin API endpoints

pom.xml, powerauth-push-client/pom.xml, powerauth-push-model/pom.xml, powerauth-push-server/pom.xml, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmClient.java
This pull request contains following changes:
- Fix #213: Support for Java 11
- Update version to 0.22.0
- Migration to Spring boot 2.1.2
- Fixed startup issue on Wildfly 'Unable to instantiate proxy using Objenesis' caused by Java 11
=> Fix #213: Support for Java 11

powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java, powerauth-push-server/src/main/java/io/getlime/push/controller/web/WebAdminController.java, powerauth-push-server/src/main/java/io/getlime/push/errorhandling/DefaultExceptionHandler.java, powerauth-push-server/src/main/java/io/getlime/push/errorhandling/WebServiceError.java, powerauth-push-server/src/main/webapp/WEB-INF/jsp/error.jsp
This pull request contains following changes:
- Fix #172: Handle possible connectivity issues to PA Server
- Show error details in error page
=> Fix #172: Handle possible connectivity issues to PA Server

powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmClient.java
This should resolve the issues for proxy host and port. 
In case we also need to set username and password, this would require an interceptor for Apache HTTP client to set the authentication header, so this is a separate improvement which will require more research.
=> Fix #244: Set proxy host and port for GoogleCredential

powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java
For now I only set `PushType.BACKGROUND` or `PushType.ALERT` depending on value of `isSilent` parameter. In future we can extend the `apns-push-type` with other push message types, I suggest to handle this as another issue.
=> Set apns-push-type for iOS 13 and higher

pom.xml, powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java
Jackson parameterized their API.
=> Upgrade Jackson and parameterize TypeReference parameter

pom.xml, powerauth-push-client/pom.xml, powerauth-push-model/pom.xml, powerauth-push-server/pom.xml, powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmClient.java
Update version to 0.24.0-SNAPSHOT
=> Fix #282: GoogleCredential is deprecated

pom.xml, powerauth-push-server/pom.xml, powerauth-push-server/src/test/java/io/getlime/push/client/PushServerTests.java
The H2 DB downgrade needs to be integrated into the release.
I also integrated the Unirest object mapper and separated the version for Push client.
=> Integrate changes from develop

powerauth-push-server/pom.xml, powerauth-push-server/src/main/java/io/getlime/push/configuration/WebApplicationConfig.java
=> Fix #291: Replace JodaTime with JSR-310

powerauth-push-server/src/main/resources/application.properties
Changes based on Spring boot 2.2 migration guide.
=> Fix #293: Update application configuration

docs/Deploying-Push-Server.md, docs/Deploying-Wildfly.md, docs/PowerAuth-Push-Server-1.0.0.md, docs/Push-Server-Integration.md, pom.xml, powerauth-push-client/pom.xml, powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java, powerauth-push-model/pom.xml, powerauth-push-server/pom.xml, powerauth-push-server/src/main/java/io/getlime/push/configuration/PowerAuthWebServiceConfiguration.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/AdministrationController.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/PushDeviceController.java, powerauth-push-server/src/main/resources/application.properties, powerauth-push-server/src/test/java/io/getlime/push/client/PushServerTests.java, powerauth-push-server/src/test/java/io/getlime/push/shared/PowerAuthTestClient.java, powerauth-push-server/src/test/java/io/getlime/push/shared/PushServerTestClientFactory.java, powerauth-push-server/src/test/resources/application-test-multiple-activations.properties, powerauth-push-server/src/test/resources/application-test.properties
This should be the last client to be migrated to WebClient.
=> Fix #312: Consider migration to WebClient

powerauth-push-server/src/main/java/io/getlime/push/configuration/PowerAuthWebServiceConfiguration.java, powerauth-push-server/src/main/resources/application.properties, powerauth-push-server/src/test/java/io/getlime/push/configuration/PushSeverTestConfiguration.java, powerauth-push-server/src/test/resources/application-test-multiple-activations.properties, powerauth-push-server/src/test/resources/application-test.properties
=> Fix #341: Remove push client instance from server

powerauth-push-model/pom.xml, powerauth-push-model/src/main/java/io/getlime/push/model/request/UpdateDeviceStatusRequest.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/PushDeviceController.java
Callback performance optimization related to https://github.com/wultra/powerauth-server/issues/451
=> Fix #317: Optimize callbacks

powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClientError.java, powerauth-push-model/src/main/java/io/getlime/push/model/entity/PushMessageSendResult.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/CreateDeviceForActivationsRequest.java, powerauth-push-server/src/main/java/io/getlime/push/configuration/BatchSendingConfiguration.java, powerauth-push-server/src/main/java/io/getlime/push/configuration/PushServiceConfiguration.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/PushMessageController.java, powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java, powerauth-push-server/src/main/java/io/getlime/push/service/apns/ApnsRejectionReason.java, powerauth-push-server/src/main/java/io/getlime/push/service/batch/SendCampaignJobListener.java, powerauth-push-server/src/main/java/io/getlime/push/service/batch/UserDeviceItemProcessor.java, powerauth-push-server/src/main/java/io/getlime/push/service/batch/UserDeviceItemWriter.java, powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/AppCredentialStorageMap.java, powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/CampaignMessageStorageMap.java, powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/UserDeviceStorageSet.java, powerauth-push-server/src/main/resources/application.properties, powerauth-push-server/src/test/java/io/getlime/push/shared/PowerAuthTestClient.java
I also fixed several inspections results in this PR.
=> Fix #346: Add support for idle ping interval in APNS

pom.xml, powerauth-push-server/pom.xml, powerauth-push-server/src/main/resources/application.properties
I also updated other dependencies and removed references to those we no longer use.
=> Fix #349: Update Pushy to 0.14.2

powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmClient.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmModelConverter.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/model/MessageWithValidation.java
Migration from generic methods call to *object method calls and simplification of FCM message serialization.
=> Fix #365: Use object methods from REST client

powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java, powerauth-push-model/src/main/java/io/getlime/push/model/entity/PushMessage.java, powerauth-push-model/src/main/java/io/getlime/push/model/enumeration/MobilePlatform.java, powerauth-push-model/src/main/java/io/getlime/push/model/enumeration/Priority.java, powerauth-push-server/src/main/java/io/getlime/push/service/PushMessageSenderService.java, powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java, powerauth-push-server/src/test/java/io/getlime/push/client/PushServerMultipleActivationsTests.java, powerauth-push-server/src/test/java/io/getlime/push/client/PushServerTests.java
- The default priority is HIGH, to assure faster push message delivery.
=> Fix #363: Evaluate priority settings for APNS and FCM

powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmModelConverter.java, powerauth-push-server/src/main/java/io/getlime/push/service/fcm/model/FcmErrorResponse.java
This change should fix the issues with resolving FCM errors. I will test it tomorrow, which is why this PR is opened as a draft right now.
=> Fix #434: Migrate to v7 error handling for FCM

powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java
=> Fix #481: Consider logging APNs/FCM error as WARN instead of INFO

pom.xml
=> Change compiler source to 17 and use implicit plugin versions

.github/workflows/codeql-analysis.yml
=> Fix #648: Add CodeQL Analysis

pom.xml, powerauth-push-server/pom.xml
=> Fix #666: Update Wultra dependencies

pom.xml, powerauth-push-client/pom.xml, powerauth-push-model/pom.xml, powerauth-push-server/pom.xml
=> Fix #664: Set release version to 1.5.0

pom.xml, powerauth-push-client/pom.xml, powerauth-push-model/pom.xml, powerauth-push-server/pom.xml
Waiting for releases of PAS 1.4.1 and lime core 1.6.2
=> Fix #700: Prepare release 1.4.3

powerauth-push-server/src/test/resources/application-test.properties
=> Remove path from h2 mem test configuration

powerauth-push-model/src/main/java/io/getlime/push/model/request/CreateApplicationRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/CreateCampaignRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/CreateDeviceForActivationsRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/CreateDeviceRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/DeleteDeviceRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/GetApplicationDetailRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/RemoveAndroidRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/RemoveIosRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/SendPushMessageBatchRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/SendPushMessageRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/TestCampaignRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/UpdateAndroidRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/UpdateDeviceStatusRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/request/UpdateIosRequest.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/CampaignResponse.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/CreateApplicationResponse.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/CreateCampaignResponse.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/DeleteCampaignResponse.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/GetApplicationDetailResponse.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/GetApplicationListResponse.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/ListOfUsersFromCampaignResponse.java, powerauth-push-model/src/main/java/io/getlime/push/model/response/ServiceStatusResponse.java, powerauth-push-server/src/main/java/io/getlime/push/controller/rest/AdministrationController.java
- Use Lombok getter and setter annotations
- Add Swagger schema annotations
- Add bean validation annotations
=> Fix #757: Cleanup request response objects

docs/Push-Message-Payload-Mapping.md, docs/_Sidebar.md, powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java, powerauth-push-server/src/main/java/io/getlime/push/service/hms/request/ClickAction.java
=> Fix and document Huawei mapping

powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java
=> Fix NPE for HMS collapse key

docs/PowerAuth-Push-Server-1.7.0.md, docs/sql/mssql/migration_1.6.0_1.7.0.sql, docs/sql/oracle/migration_1.6.0_1.7.0.sql, docs/sql/postgresql/migration_1.6.0_1.7.0.sql
(cherry picked from commit 98703d8ff424c1e43704ebb513336ee70f9e0cc4)
=> Fix #868: Add missing SQL migration script for 1.7.0 (backport)

pom.xml
- Update maven-javadoc-plugin configuration to use delomboked sources.
- Fix MavenReportException: Error while generating Javadoc.
=> Fix #866: Javadoc error
