- powerauth-push-server/src/main/java/io/getlime/push/controller/web/model/form/UploadIosCredentialsForm.java
Relaxed validation regexp to allow '-' character
> Fix #60: Push Credentials Setup - invalid iOS bundle ID

- powerauth-push-server/src/main/java/io/getlime/push/service/PushMessageSenderService.java
- powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmClient.java
There is still some small room for improvement in the synchronization aspect. There might be unexpected and awkward runtime exceptions thrown while sending push notification (out of memory issue, etc.) and in this case, the phaser is not deregistered again and will cause server to hang.
However, the current handling should be generic enough to account for:
- Database errors.
- Errors during network communication that is done when sending push notifications to APNS/FCM.
> Fix #86: Server hangs on database issue

- docs/sql/mysql/create_push_server_schema.sql
- powerauth-push-server/src/main/java/io/getlime/push/repository/model/AppCredentialsEntity.java
- powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushCampaignEntity.java
- powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushCampaignUserEntity.java
- powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushDeviceRegistrationEntity.java
- powerauth-push-server/src/main/java/io/getlime/push/repository/model/PushMessageEntity.java
Change description:
* Removed `@GenericGenerator` to avoid ID generator name conflict, `@SequenceGenerator` is used in all production databases
* ID generation strategy switched to `TABLE` for MySQL (due to changed default in Hibernate 5, MySQL is only used for development, thus performance issues related to row level database locking do not matter)
> Fix #121: Warning during startup due to sequence generator names

- powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java
- powerauth-push-model/src/main/java/io/getlime/push/model/entity/PushServerApplication.java
- powerauth-push-model/src/main/java/io/getlime/push/model/request/CreateApplicationRequest.java
- powerauth-push-model/src/main/java/io/getlime/push/model/request/GetApplicationDetailRequest.java
- powerauth-push-model/src/main/java/io/getlime/push/model/request/RemoveAndroidRequest.java
- powerauth-push-model/src/main/java/io/getlime/push/model/request/RemoveIosRequest.java
- powerauth-push-model/src/main/java/io/getlime/push/model/request/UpdateAndroidRequest.java
- powerauth-push-model/src/main/java/io/getlime/push/model/request/UpdateIosRequest.java
- powerauth-push-model/src/main/java/io/getlime/push/model/response/CreateApplicationResponse.java
- powerauth-push-model/src/main/java/io/getlime/push/model/response/GetApplicationDetailResponse.java
- powerauth-push-model/src/main/java/io/getlime/push/model/response/GetApplicationListResponse.java
- powerauth-push-server/pom.xml
- powerauth-push-server/src/main/java/io/getlime/push/configuration/PowerAuthWebServiceConfiguration.java
- powerauth-push-server/src/main/java/io/getlime/push/controller/rest/AdministrationController.java
- powerauth-push-server/src/main/java/io/getlime/push/controller/web/WebAdminController.java
- powerauth-push-server/src/main/resources/application.properties
- powerauth-push-server/src/main/webapp/WEB-INF/jsp/applicationCreate.jsp
- powerauth-push-server/src/main/webapp/WEB-INF/jsp/error.jsp
This PR adds REST API for administration in Push Server.
I haven't removed the web interface in Push Server yet, it was migrated to REST API instead. The web controller code will be reused in PA universal admin, so it should not be an worthless effort. We can remove the web interface completely once PA universal admin is available.
@hvge I am adding you as reviewer as agreed with @petrdvorak.
> Add admin REST API and migrate web interface to the REST API

- powerauth-push-server/src/main/java/io/getlime/push/configuration/PowerAuthWebServiceConfiguration.java
- powerauth-push-server/src/main/resources/application.properties
The temporary REST service location code was working only for Tomcat and failed on Wildfly.
I added a configuration parameter to specify the service location (so that the code is container independent).
> Fix #190: NoSuchElementException thrown during startup on Wildfly

- README.md
- docs/Deploying-Push-Server.md
- docs/Home.md
- docs/Migration-Instructions.md
- docs/PowerAuth-Push-Server-0.21.0.md
- docs/Push-Message-Payload-Mapping.md
- docs/Push-Server-API.md
- docs/Push-Server-Database.md
- docs/Push-Server-Integration.md
- docs/Running-Behind-Proxy.md
- docs/_Sidebar.md
This pull request contains following changes:
- Fix #196: Migrate documentation from GitHub wiki to code
- Documentation updates for release 0.21.0
- Updated links due to migration from wiki to code
- Updated DDL and database structure
> Fix #196: Migrate documentation from GitHub wiki to code

- powerauth-push-server/src/main/java/io/getlime/push/configuration/PushServiceConfiguration.java
- powerauth-push-server/src/main/java/io/getlime/push/service/PushSendingWorker.java
- powerauth-push-server/src/main/java/io/getlime/push/service/fcm/FcmClient.java
- powerauth-push-server/src/main/resources/application.properties
I made the FCM URL configurable so that we can test Push Server performance with our own endpoint.
> Fix #133: Make FCM URL configurable

- docs/PowerAuth-Push-Server-0.21.0.md
- docs/sql/mysql/create_push_server_schema.sql
The original index definition failed in Docker while it worked fine on my newer version of MySQL.
> Fix #218: Use case sensitive index definition for MySQL

- docs/Deploying-Push-Server.md
- docs/Deploying-Wildfly.md
- docs/_Sidebar.md
- powerauth-push-server/src/main/java/io/getlime/push/configuration/PushServiceConfiguration.java
- powerauth-push-server/src/main/resources/application.properties
- powerauth-push-server/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
This pull request adds the deployment descriptor for JBoss / Wildfly and activates the `ext` profile to allow overriding of `application.properties`. It also includes documentation updates especially about deploying on JBoss / Wildfly.
> Fix #221: Add jboss-deployment-structure.xml file

- powerauth-push-server/pom.xml
It is not easy to move the FCM model classes to our project because there are many other Google library dependencies in these classes. So at least I excluded the problematic depedencies reported by OWASP check.
> Fix #229: Replace firebase-admin dependency

- pom.xml
- powerauth-push-server/pom.xml
This pull request contains following dependency updates:
- Update of `pushy` dependency
- Parameterized `jstl` dependency version
- Removed `reactor-netty` dependency, it is no longer needed in Spring boot `2.1.5`
> Fix #233: Update Pushy dependency

- pom.xml
- powerauth-push-server/src/test/java/io/getlime/push/shared/PowerAuthTestClient.java
- powerauth-push-server/src/test/java/io/getlime/push/shared/PushServerTestClientFactory.java
This pull request removes the crypto provider abstraction and updates the PowerAuth version to `0.24.0-SNAPSHOT`.
> Fix #284: Deprecate crypto provider abstraction

- powerauth-push-server/src/main/java/io/getlime/push/errorhandling/DataIntegrityError.java
- powerauth-push-server/src/main/java/io/getlime/push/errorhandling/DefaultExceptionHandler.java
The data integrity error is handled and a 409 - CONFLICT HTTP status is returned instead of a generic 500 error. The error is still logged, because the error should not occur when the client is correctly implemented, we still want to find out when the client sends duplicate requests.
> Fix #334: Integrity check issues

- powerauth-push-server/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
The JAX-RS subsystem of Wildfly ships with old version of Jackson libraries which are not compatible with current versions of Jackson used in Push Server. I tried to disable the Jackson modules individually, but it didn't help. After excluding the JAX-RS subsystem Push server starts on Wildfly without any issues.
> Fix #373: Push server fails to start on Wildfly

- powerauth-push-client/pom.xml
- powerauth-push-model/pom.xml
- powerauth-push-server/pom.xml
This change should resolve any future questions about the Log4J dependencies included in Spring logging.
> Fix #447: Exclude log4j-api dependency

- docs/db/changelog/changesets/powerauth-push-server/1.4.x/20230321-init-db.xml
> Add missing push_campaign.timestamp_sent column to liquibase

- pom.xml
- powerauth-push-server/pom.xml
- update google-api-client to 1.35.2
- drop explicit guava declaration
> Fix #661: Polish google-api-client and guava versions

- docs/db/changelog/changesets/powerauth-push-server/1.4.x/20230321-init-db.xml
> Fix #670: Review liquibase scripts

- .github/workflows/codeql-analysis.yml
> Remove javascript from CodQL configuration

- powerauth-push-server/src/main/resources/application.properties
- Exclude `UserDetailsServiceAutoConfiguration`
> Fix #739: Warning: Using generated security password

- docs/Deploying-Wildfly.md
- pom.xml
- powerauth-push-server/pom.xml
Use transient dependency from `powerauth-crypto` which is scope `test`.
> Fix #824: Refactor BouncyCastle dependency

- docs-private/Developer-How-To-Start.md
- docs/Migration-Instructions.md
- docs/PowerAuth-Push-Server-1.8.0.md
- docs/db/changelog/changesets/powerauth-push-server/1.8.x/20240708-column-renaming-keywords.xml
- docs/db/changelog/changesets/powerauth-push-server/1.8.x/db.changelog-version.xml
- docs/db/changelog/changesets/powerauth-push-server/db.changelog-module.xml
- docs/sql/mssql/create_push_server_schema.sql
- docs/sql/mssql/migration_1.7.0_1.8.0.sql
- docs/sql/oracle/create_push_server_schema.sql
- docs/sql/oracle/migration_1.7.0_1.8.0.sql
- docs/sql/postgresql/create_push_server_schema.sql
- docs/sql/postgresql/migration_1.7.0_1.8.0.sql
- powerauth-push-server/src/main/java/io/getlime/push/repository/InboxRepository.java
- powerauth-push-server/src/main/java/io/getlime/push/repository/converter/InboxMessageConverter.java
- powerauth-push-server/src/main/java/io/getlime/push/repository/model/InboxMessageEntity.java
- powerauth-push-server/src/main/java/io/getlime/push/service/InboxService.java
Due to problems with column name escaping in Oracle caused by enforced case sensitivity I had to rename the two columns which are problematic keywords in MSSQL.
> Fix #861: SQL error after DB column escaping

- powerauth-push-server/src/main/java/io/getlime/push/service/PushMessageSenderService.java
- powerauth-push-server/src/test/java/io/getlime/push/controller/MockPowerAuthController.java
- powerauth-push-server/src/test/java/io/getlime/push/tests/PushServerTests.java
Add warning when push notification cannot be sent due to an invalid userId or userId+activationId combination
> Fix #841: Add warning when push notification cannot be sent
